name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: runner
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-try:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY}}

      - name: Deploy to Cloud Run 
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: my-nextjs-app
          region: us-central1
          image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/docker-try:latest
          env_vars: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
